# _config.yml
title: ğŸ“&ğŸŒ•
description: An emotional logic archive by SWHCZ (a.k.a. strawberrymoonshot)
theme: just-the-docs
color_scheme: strawberry

url: https://strawberrymoonshot.github.io/strawberrymoonstruck

aux_links:
  Template Repository: https://github.com/strawberrymoonshot/strawberrymoonstruck
